plugins {
    id 'com.android.application'
}

android {
    namespace 'de.bulling.barcodebuddyscanner'
    compileSdk 37

    defaultConfig {
        applicationId "de.bulling.barcodebuddyscanner"
        minSdkVersion 24
        targetSdkVersion 37
        versionCode 10
        versionName "0.4.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        // Enables BuildConfig generation locally for this module
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debugPublic {
            debuggable true
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // AndroidX & Material UI
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.preference:preference:1.2.1'

    // Gson for JSON parsing:
    implementation 'com.google.code.gson:gson:2.14.0'

    // Barcode Scanner
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}